In [8]:
import sys
sys.path.insert(1, '/usr/local/lib64/python2.7/site-packages')
sys.path.insert(1, '/usr/local/share/gwyddion/pygwy/')
import gwy

import numpy as np
import gwyutils
#import skimage.io

In [26]:
data_path ='/home/jorghyq/Data/201607_I/F160730.003926.R.dat'
c = gwy.gwy_app_file_load(data_path)
#dfields = gwyutils.get_data_fields_dir(c)
data = c['/0/data']
meta = c['/0/meta']
title = c['/4/data/title']
print title
channel = c['/0/data/title']
print channel
array = gwyutils.data_field_data_as_array(data)
print c.keys_by_name()
print meta.keys_by_name()
print meta['Biasvolt[mV]']
print meta['Channels / Channels']
print array

Topography
Topography
('/2/data', '/2/data/title', '/2/data/log', '/0/data', '/0/data/title', '/3/data/title', '/3/data', '/4/data', '/3/data/log', '/4/data/log', '/4/data/title', '/5/data/title', '/5/data', '/6/data', '/0/meta', '/6/data/log', '/0/data/log', '/1/data', '/1/data/title', '/1/data/log', '/7/data/log', '/5/data/log', '/7/data/title', '/6/data/title', '/filename', '/7/data', '/0/data/visible')
('ActGainXYZ', 'AproBurst', 'AproPeriod', 'BiasVoltage / BiasVolt.[mV]', 'Biasvolt[mV]', 'CHModeGainpreamp / CHModeGainpreamp', 'CHModeZoff / CHModeZoff', 'Chan(1,2,4) / Chan(1,2,4)', 'Channels / Channels', 'Channels', 'CurrentRC', 'Current[A]', 'D-DeltaX / D-DeltaX', 'DAC-Type', 'DAC5[V]', 'DSP_Clock', 'Dacto[A]xy', 'Dacto[A]z', 'Delay X+ / Delay X+', 'Delay X- / Delay X-', 'Delay Y / Delay Y', 'Delta X / Delta X [Dac]', 'Delta Y / Delta Y [Dac]', 'DigZoomX', 'DigZoomZ', 'FBIntegral', 'FBLogIset', 'FBLog', 'FBProp', 'FBVoltGain', 'FBVoltRC', 'FFTPoints', 'Frameimageoffset', 'GainX /

In [3]:
array.dtype

dtype('float64')

In [13]:
print array
print array.max()
print array.min()

[[-6.49736166 -7.11268091 -4.36813641 ..., -5.55341911 -3.74829555
  -5.11492252]
 [-6.19998455 -6.46459866 -4.41258287 ..., -5.63133717 -4.85614681
  -5.17203474]
 [-5.47238016 -5.84735775 -4.1970396  ..., -5.3273716  -5.5087018
  -5.31955004]
 ..., 
 [-5.49646473 -4.49451923 -3.85524178 ..., -4.36877346 -4.90596628
  -4.57403851]
 [-4.62971687 -5.11021233 -6.61363983 ..., -4.99949837 -4.81503773
  -5.60033512]
 [-4.48569012 -5.02195549 -7.42216492 ..., -5.45249319 -4.61635923
  -5.22233677]]
-0.468591928482
-11.5749015808


In [4]:
array2 = array * 1e9

In [5]:
print array2

[[ -6.49736166e+09  -7.11268091e+09  -4.36813641e+09 ...,  -5.55341911e+09
   -3.74829555e+09  -5.11492252e+09]
 [ -6.19998455e+09  -6.46459866e+09  -4.41258287e+09 ...,  -5.63133717e+09
   -4.85614681e+09  -5.17203474e+09]
 [ -5.47238016e+09  -5.84735775e+09  -4.19703960e+09 ...,  -5.32737160e+09
   -5.50870180e+09  -5.31955004e+09]
 ..., 
 [ -5.49646473e+09  -4.49451923e+09  -3.85524178e+09 ...,  -4.36877346e+09
   -4.90596628e+09  -4.57403851e+09]
 [ -4.62971687e+09  -5.11021233e+09  -6.61363983e+09 ...,  -4.99949837e+09
   -4.81503773e+09  -5.60033512e+09]
 [ -4.48569012e+09  -5.02195549e+09  -7.42216492e+09 ...,  -5.45249319e+09
   -4.61635923e+09  -5.22233677e+09]]


In [2]:
b = skimage.io.imread('/home/jorghyq/Project/GwyUtils/test/A150716.115105-00353.png')

In [3]:
print b

[[[196  53  45]
  [205  78  39]
  [217 110  32]
  ..., 
  [204  75  40]
  [210  91  36]
  [208  87  37]]

 [[221 122  29]
  [215 107  33]
  [204  76  40]
  ..., 
  [219 116  31]
  [217 113  31]
  [210  91  36]]

 [[173  47  53]
  [169  47  54]
  [178  47  51]
  ..., 
  [173  47  53]
  [170  47  53]
  [183  46  49]]

 ..., 
 [[178  47  51]
  [177  47  51]
  [167  47  54]
  ..., 
  [214 103  34]
  [207  84  38]
  [208  86  37]]

 [[199  60  43]
  [198  56  44]
  [209  88  37]
  ..., 
  [222 125  29]
  [224 147  28]
  [225 157  28]]

 [[205  78  39]
  [199  60  43]
  [198  58  44]
  ..., 
  [224 147  28]
  [222 127  28]
  [222 126  28]]]


In [44]:
print b
print b.dtype
z = b.astype('uint16')
print z.dtype
print b.max()
print b.min()
skimage.io.imsave('test.png',z)

[[29961 31716 36009 ..., 35867 40982 41831]
 [26330 30154 33797 ..., 41779 38146 38667]
 [42525 42263 43535 ..., 45552 29275 24504]
 ..., 
 [35531 35071 36865 ..., 42521 38800 36127]
 [46183 39645 35795 ..., 39351 39888 41060]
 [38118 37781 36911 ..., 41310 35254 37485]]
int32
uint16
65535
0


In [77]:
from PIL import ImageFont
from PIL import Image
from PIL import ImageDraw
import numpy as np

img = Image.open("./test.png")
I = np.asarray(img)
print I.dtype
w,h = I.shape
new = np.zeros((w+40,h))
new[:,:] = 65535
new[:w,:h] = I
print new
print new.dtype
new = new.astype('int32')
img = Image.fromarray(new)
draw = ImageDraw.Draw(img)
font = ImageFont.truetype("/usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-B.ttf",30)
draw.rectangle([0,0,200,40],fill=65535)
draw.text((0, w),"Sample Text",font=font,fill=0)

img.save('sample-out.png')

int32
[[ 29961.  31716.  36009. ...,  35867.  40982.  41831.]
 [ 26330.  30154.  33797. ...,  41779.  38146.  38667.]
 [ 42525.  42263.  43535. ...,  45552.  29275.  24504.]
 ..., 
 [ 65535.  65535.  65535. ...,  65535.  65535.  65535.]
 [ 65535.  65535.  65535. ...,  65535.  65535.  65535.]
 [ 65535.  65535.  65535. ...,  65535.  65535.  65535.]]
float64


In [78]:
from PIL import ImageFont
from PIL import Image
from PIL import ImageDraw
import numpy as np

img = Image.open("./test.png")
draw = ImageDraw.Draw(img)
font = ImageFont.truetype("/usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-B.ttf",30)
draw.rectangle([0,0,200,40],fill=65535)
draw.text((0, 0),"Sample Text",font=font,fill=0)

img.save('sample-out.png')

In [9]:
import matplotlib.pyplot as plt
imgplot = plt.imshow(b)
imgplot.set_cmap('gray')
plt.show()

In [15]:
import Image
#print Image.__version__
h,w = array.shape
print h,w
im = Image.fromarray(array2)
#im.point()
print im.size
print im.mode
table=[ i/256 for i in range(65536) ]
im2 = im.point(table,'L')
im2.save('test_16bit.png')

1024 1024
(1024, 1024)
F


ValueError: point operation not supported for this mode

In [39]:
import numpy as np
from skimage import io, exposure, img_as_uint, img_as_float




array4 = exposure.rescale_intensity(-array, out_range='float')
array4 = img_as_uint(array4)
c = img_as_uint(b)
print b.dtype
io.imsave('test_16bit2.png', b)
#plt.imshow(array4)
print b
print c
print np.transpose(array4)
#print array4
print array4.max()
print array4.min()

int32


TypeError: Cannot save image of this format to this file type

In [18]:
import numpy as np
from skimage import io, exposure, img_as_uint, img_as_float
io.use_plugin('freeimage')
#im = np.array([[1., 2.], [3., 4.]], dtype='float64')
im = np.array([[1., 2.], [3., 4.]], dtype='float64')
im = exposure.rescale_intensity(-im, out_range='float')
im = img_as_uint(im)
im

array([[65535, 21845],
       [    0,     0]], dtype=uint16)